In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [50]:
dataset = pd.read_csv("DataSet_for_ANN.csv")

In [51]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [52]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [53]:
X[0:5]
# BEFORE

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [54]:
le = LabelEncoder()
X[:,2]= le.fit_transform(X[:,2])

In [55]:
X[0:5]
# AFTER

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [56]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder='passthrough')

In [57]:
X[0:5]
# BEFORE

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [58]:
X = np.array(ct.fit_transform(X))

In [59]:
# AFTER
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [60]:
 X_train, X_test, y_train, y_test = train_test_split(
 X,y,test_size=0.2,random_state=1)

In [61]:
X_train

array([[0.0, 1.0, 0.0, ..., 0, 1, 124749.08],
       [1.0, 0.0, 0.0, ..., 0, 0, 41104.82],
       [0.0, 1.0, 0.0, ..., 1, 1, 45750.21],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 1, 92027.69],
       [1.0, 0.0, 0.0, ..., 1, 1, 101168.9],
       [0.0, 1.0, 0.0, ..., 1, 0, 33462.94]], dtype=object)

In [62]:
print(X_train.shape[0])

8000


In [63]:
sc = StandardScaler()

In [64]:
X_train = sc.fit_transform(X_train)

In [65]:
X_train

array([[-0.99850112,  1.71490137, -0.57273139, ..., -1.55337352,
         0.97725852,  0.42739449],
       [ 1.00150113, -0.58312392, -0.57273139, ..., -1.55337352,
        -1.02327069, -1.02548708],
       [-0.99850112,  1.71490137, -0.57273139, ...,  0.64376017,
         0.97725852, -0.94479772],
       ...,
       [ 1.00150113, -0.58312392, -0.57273139, ...,  0.64376017,
         0.97725852, -0.14096853],
       [ 1.00150113, -0.58312392, -0.57273139, ...,  0.64376017,
         0.97725852,  0.01781218],
       [-0.99850112,  1.71490137, -0.57273139, ...,  0.64376017,
        -1.02327069, -1.15822478]])

In [66]:
X_test[0:5]

array([[1.0, 0.0, 0.0, 550, 1, 47, 2, 0.0, 2, 1, 1, 97057.28],
       [1.0, 0.0, 0.0, 680, 1, 34, 3, 143292.95, 1, 1, 0, 66526.01],
       [1.0, 0.0, 0.0, 531, 0, 42, 2, 0.0, 2, 0, 1, 90537.47],
       [0.0, 1.0, 0.0, 710, 1, 34, 8, 147833.3, 2, 0, 1, 1561.58],
       [0.0, 1.0, 0.0, 543, 1, 30, 6, 73481.05, 1, 1, 1, 176692.65]],
      dtype=object)

In [67]:
X_test = sc.transform(X_test)
X_test[0:5]

array([[ 1.00150113, -0.58312392, -0.57273139, -1.03768121,  0.91509065,
         0.77498705, -1.0482813 , -1.22599173,  0.80225696,  0.64376017,
         0.97725852, -0.05360571],
       [ 1.00150113, -0.58312392, -0.57273139,  0.30708683,  0.91509065,
        -0.46686456, -0.70174202,  1.07152411, -0.91150957,  0.64376017,
        -1.02327069, -0.58392685],
       [ 1.00150113, -0.58312392, -0.57273139, -1.23422423, -1.09278791,
         0.29735181, -1.0482813 , -1.22599173,  0.80225696, -1.55337352,
         0.97725852, -0.16685331],
       [-0.99850112,  1.71490137, -0.57273139,  0.61741792,  0.91509065,
        -0.46686456,  1.03095433,  1.14432271,  0.80225696, -1.55337352,
         0.97725852, -1.71234407],
       [-0.99850112,  1.71490137, -0.57273139, -1.11009179,  0.91509065,
        -0.84897275,  0.33787579, -0.04781879, -0.91150957,  0.64376017,
         0.97725852,  1.32964236]])

In [68]:
import tensorflow as tf
tf.__version__


'2.12.0'

In [75]:
ann = tf.keras.models.Sequential()

In [76]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [77]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [78]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [79]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics = ["accuracy"])

In [81]:
results = ann.fit(X_train, y_train, batch_size=8,epochs=100)

Epoch 1/100
1000/1000 [==============================] - 1s 776us/step - loss: 0.3390 - accuracy: 0.8610
Epoch 2/100
1000/1000 [==============================] - 1s 779us/step - loss: 0.3382 - accuracy: 0.8609
Epoch 3/100
1000/1000 [==============================] - 1s 766us/step - loss: 0.3375 - accuracy: 0.8605
Epoch 4/100
1000/1000 [==============================] - 1s 765us/step - loss: 0.3377 - accuracy: 0.8611
Epoch 5/100
1000/1000 [==============================] - 1s 770us/step - loss: 0.3374 - accuracy: 0.8605
Epoch 6/100
1000/1000 [==============================] - 1s 764us/step - loss: 0.3373 - accuracy: 0.8618
Epoch 7/100
1000/1000 [==============================] - 1s 763us/step - loss: 0.3370 - accuracy: 0.8587
Epoch 8/100
1000/1000 [==============================] - 1s 765us/step - loss: 0.3365 - accuracy: 0.8614
Epoch 9/100
1000/1000 [==============================] - 1s 759us/step - loss: 0.3363 - accuracy: 0.8605
Epoch 10/100
1000/1000 [==============================]

1000/1000 [==============================] - 1s 769us/step - loss: 0.3339 - accuracy: 0.8616
Epoch 79/100
1000/1000 [==============================] - 1s 778us/step - loss: 0.3346 - accuracy: 0.8624
Epoch 80/100
1000/1000 [==============================] - 1s 797us/step - loss: 0.3342 - accuracy: 0.8625
Epoch 81/100
1000/1000 [==============================] - 1s 796us/step - loss: 0.3340 - accuracy: 0.8625
Epoch 82/100
1000/1000 [==============================] - 1s 798us/step - loss: 0.3338 - accuracy: 0.8637
Epoch 83/100
1000/1000 [==============================] - 1s 786us/step - loss: 0.3342 - accuracy: 0.8629
Epoch 84/100
1000/1000 [==============================] - 1s 779us/step - loss: 0.3341 - accuracy: 0.8620
Epoch 85/100
1000/1000 [==============================] - 1s 775us/step - loss: 0.3339 - accuracy: 0.8629
Epoch 86/100
1000/1000 [==============================] - 1s 777us/step - loss: 0.3336 - accuracy: 0.8630
Epoch 87/100
1000/1000 [==============================] - 1

In [82]:
ann.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 6)                 78        
                                                                 
 dense_16 (Dense)            (None, 6)                 42        
                                                                 
 dense_17 (Dense)            (None, 1)                 7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [83]:
y_pred = ann.predict(X_test)
y_pred = (y_pred >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1))))

63/63 [==============================] - 0s 567us/step
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [86]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1524   61]
 [ 211  204]]


0.864

In [ ]:
print(ann.predict(sc.transform()))